### ISSUE TITLE
https port issue

### ISSUE THREAD

**Issue by zerostress99** [madchicken/comelit-client#14]
Hi Pierpaolo, first of all let me say this is a very useful CLI to interact with Comelit modules.
Unfortunately though, it seems that I cannot reach modules via HTPPS (443) but only on HTTP (80) port. 
Do you know why? Serial Bridge or Vedo modules accepts incoming traffic via HTTPS?
Here is a snippet error code I got.
Ah just to be friendly I also come from Vercelli (...near)

comelit-sb -p 443 -h 192.168.1.252 rooms --list

Executing command rooms - {"_":["rooms"],"p":443,"port":443,"h":"192.168.1.252","host":"192.168.1.252","list":true,"$0":"AppData\\Roaming\\npm\\node_modules\\comelit-client\\dist\\bin\\comelit-sb-cli.js"}
(node:7188) UnhandledPromiseRejectionWarning: Error: timeout of 3000ms exceeded
    at createError (C:\Users\zero\AppData\Roaming\npm\node_modules\comelit-client\node_modules\axios\lib\core\createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (C:\Users\zero\AppData\Roaming\npm\node_modules\comelit-client\node_modules\axios\lib\adapters\http.js:264:16)
    at Object.onceWrapper (events.js:421:28)
    at RedirectableRequest.emit (events.js:315:20)
    at Timeout._onTimeout (C:\Users\zero\AppData\Roaming\npm\node_modules\comelit-client\node_modules\follow-redirects\index.js:166:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

PS: I notice that though my router is already set to forwarding https ports for each modules when the requests coming from web (via dns comelit) it is very very slow. Do you know what happens? 
PS: Do you plan to extend commands to be more amministrative? modify or restart modules et so on..

**Comment by zerostress99** [comment]
duplicate
